name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2mypkg/
          cd /root/ros2_ws
          python3 -m pip install --upgrade pip
          pip install yfinance
          bash -xv ./src/ros2mypkg/test/test.bash /root
