name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
        
# Pythonの依存関係をインストール
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install yfinance

      # ROS 2パッケージをビルド
      - name: Build ROS2 package
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2mypkg/
          cd /root/ros2_ws
          colcon build
          source install/setup.bash

      # テストスクリプトを実行
      - name: Run tests
        run: |
          cd /root/ros2_ws
          bash -xv ./src/ros2mypkg/test/test.bash /root
