name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pip
        run: |
          apt-get update && apt-get install -y python3-pip
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install yfinance
      - name: Build ROS2 package
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2mypkg/
          cd /root/ros2_ws
          colcon build
      - name: Run tests
        run: |
          cd /root/ros2_ws
          bash -xv ./src/ros2mypkg/test/test.bash /root
