name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt update -y
          apt install -y python3-pip
          pip3 install yfinance
      - name: Build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/ros2mypkg/
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root

